-- Setup y Seed de Base de Datos para Nintendo Vault en Supabase

-- 1. Crear tabla 'games' si no existe
CREATE TABLE IF NOT EXISTS public.games (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    platform TEXT NOT NULL,
    platform_slug TEXT NOT NULL,
    genre TEXT NOT NULL,
    genre_slug TEXT NOT NULL,
    release_year INTEGER NOT NULL,
    developer TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    source_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Asegurar columnas si la tabla ya existía previamente
ALTER TABLE public.games ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.games ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'Nintendo 64';
ALTER TABLE public.games ADD COLUMN IF NOT EXISTS platform_slug TEXT DEFAULT 'n64';

-- 2. Habilitar Row Level Security (RLS)
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- 3. Política de lectura pública (SELECT)
DROP POLICY IF EXISTS "Public Read Games" ON public.games;
DROP POLICY IF EXISTS "Permitir lectura pública de juegos" ON public.games;
CREATE POLICY "Public Read Games"
    ON public.games
    FOR SELECT
    USING (true);

-- 4. Poblar datos oficiales con slugs legibles (Upsert usando id)
INSERT INTO public.games (id, slug, title, platform, platform_slug, genre, genre_slug, release_year, developer, description, image_url, source_url)
VALUES
('cc51e385-be8d-55a9-a9da-f019233636a6', 'pokemon-emerald', 'Pokémon Emerald', 'Game Boy Advance', 'gba', 'RPG', 'rpg', 2004, 'Game Freak', 'Pokémon Esmeralda es un videojuego de rol de 2004 desarrollado por Game Freak y publicado por The Pokémon Company y Nintendo para Game Boy Advance. Es la versión definitiva y ampliada de la tercera generación en la región de Hoenn, incorporando la emblemática Batalla de la Frontera (Frente de Batalla) y la trama centrada en el legendario Rayquaza para calmar el conflicto entre Groudon y Kyogre.', 'https://upload.wikimedia.org/wikipedia/en/f/f7/PokemonEmeraldBox.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Pokemon_Emerald'),
('a1e498f9-359d-51d2-a909-ff00c85b8c13', 'zelda-minish-cap', 'The Legend of Zelda: The Minish Cap', 'Game Boy Advance', 'gba', 'Aventura', 'aventura', 2004, 'Capcom', 'The Legend of Zelda: The Minish Cap es un juego de acción y aventura desarrollado por Capcom y Flagship junto a Nintendo para Game Boy Advance. Narra el origen de la Espada Cuádruple y el malvado hechicero Vaati, introduciendo a Ezero, un sombrero mágico parlante que otorga a Link la habilidad de encogerse al diminuto tamaño de la raza Minish para explorar templos y mazmorras ocultas.', 'https://upload.wikimedia.org/wikipedia/en/0/0a/TLOZ-_Minish_Cap_NA_Box_art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_The_Minish_Cap'),
('9a08b216-fc84-53c5-9e32-c8912b8ff903', 'metroid-fusion', 'Metroid Fusion', 'Game Boy Advance', 'gba', 'Acción', 'accion', 2002, 'Nintendo R&D1', 'Metroid Fusion es un videojuego de acción y aventura de desplazamiento lateral lanzado en 2002 para Game Boy Advance. Desarrollado por Nintendo R&D1, pone a los jugadores al mando de la cazarrecompensas Samus Aran, quien debe investigar los laboratorios de investigación biológica BSL infectados por el parásito X, mientras es acechada incansablemente por el SA-X, un clon letal con su máximo poder.', 'https://upload.wikimedia.org/wikipedia/en/4/45/Metroid_Fusion_box.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Metroid_Fusion'),
('0f14cfec-aca8-59dd-b40a-6d8540dcfda7', 'golden-sun', 'Golden Sun', 'Game Boy Advance', 'gba', 'RPG', 'rpg', 2001, 'Camelot Software Planning', 'Golden Sun es un aclamado videojuego de rol lanzado en 2001 por Camelot Software Planning y Nintendo para Game Boy Advance. Sigue la odisea de un grupo de jóvenes Adeptos liderados por Hans (Isaac) que dominan la Psinergía y deben recorrer el mundo de Weyard para evitar que los cuatro faros elementales sean encendidos, lo que liberaría el destructivo poder primordial de la Alquimia.', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Golden_Sun_video_game_box_art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Golden_Sun_(video_game)'),
('cf71ce58-9b75-57eb-a09b-c5eea0eec149', 'castlevania-aria-of-sorrow', 'Castlevania: Aria of Sorrow', 'Game Boy Advance', 'gba', 'Acción', 'accion', 2003, 'Konami', 'Castlevania: Aria of Sorrow es un juego de acción y exploración de estilo ''Metroidvania'' publicado por Konami en 2003 para Game Boy Advance. Ambientado en el año 2035, sigue a Soma Cruz, un estudiante atrapado en el castillo de Drácula durante un eclipse solar, quien posee el exclusivo ''Poder del Dominio'' que le permite absorber y utilizar las almas y habilidades de los monstruos derrotados.', 'https://upload.wikimedia.org/wikipedia/en/a/ab/AriaofSorrowCover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Castlevania:_Aria_of_Sorrow'),
('c5db4e10-d760-507f-8774-c44467e76028', 'advance-wars', 'Advance Wars', 'Game Boy Advance', 'gba', 'Estrategia', 'estrategia', 2001, 'Intelligent Systems', 'Advance Wars es un célebre videojuego de estrategia táctica por turnos desarrollado por Intelligent Systems y lanzado en 2001 para Game Boy Advance. Los jugadores asumen el rol de Oficiales en Jefe (CO) del ejército de Orange Star, dirigiendo unidades terrestres, marítimas y aéreas a través de cuadrículas estratégicas para neutralizar a las fuerzas enemigas y asegurar cuarteles clave.', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Advance_Wars_Coverart.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Advance_Wars'),
('fdced8be-e7e5-58a2-8735-7e73fd98460e', 'mario-luigi-superstar-saga', 'Mario & Luigi: Superstar Saga', 'Game Boy Advance', 'gba', 'RPG', 'rpg', 2003, 'AlphaDream', 'Mario & Luigi: Superstar Saga es un juego de rol cómico desarrollado por AlphaDream y lanzado en 2003 para Game Boy Advance. Los hermanos fontaneros viajan al Reino Judía para recuperar la voz robada de la Princesa Peach de manos de la bruja Cackletta y su secuaz Fawful, utilizando un innovador sistema de combate por turnos sincronizado donde cada botón controla a un hermano simultáneamente.', 'https://upload.wikimedia.org/wikipedia/en/6/63/MarioAndLuigiSuperstarSagaGBACoverArtUS.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Mario_%26_Luigi:_Superstar_Saga'),
('10c8f185-edda-5bf0-971e-0b55466b986b', 'fire-emblem-blazing-blade', 'Fire Emblem', 'Game Boy Advance', 'gba', 'Estrategia', 'estrategia', 2003, 'Intelligent Systems', 'Fire Emblem: The Blazing Blade es un videojuego de rol táctico desarrollado por Intelligent Systems y lanzado en 2003 para Game Boy Advance, siendo el primer título de la aclamada saga en ser localizado y publicado internacionalmente. Sigue a Lyn, Eliwood y Hector en una conspiración a gran escala en el continente de Elibe, combinando combate por cuadrículas estratégicas con muerte permanente de personajes.', 'https://upload.wikimedia.org/wikipedia/en/e/e2/GBA_Fire_Emblem_Box.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Fire_Emblem_(video_game)'),
('8a039f42-2486-5c5a-a4cd-9746ce23a6c9', 'super-mario-advance-4', 'Super Mario Advance 4: Super Mario Bros. 3', 'Game Boy Advance', 'gba', 'Plataformas', 'plataformas', 2003, 'Nintendo EAD', 'Super Mario Advance 4: Super Mario Bros. 3 es una adaptación completa y remasterizada del legendario clásico de NES para Game Boy Advance, lanzada en 2003. Incluye gráficos y audio renovados, mecánicas de transformación como Mario Tanuki y Mario Rana, física pulida y compatibilidad con niveles especiales mediante la tecnología e-Reader.', 'https://upload.wikimedia.org/wikipedia/en/9/9f/Super_Mario_Advance_4_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Super_Mario_Advance_4:_Super_Mario_Bros._3'),
('98b1694f-cfb0-516a-b98c-33ed7c6e33dc', 'mega-man-battle-network', 'Mega Man Battle Network', 'Game Boy Advance', 'gba', 'RPG', 'rpg', 2001, 'Capcom', 'Mega Man Battle Network es un videojuego de rol táctico en tiempo real creado por Capcom en 2001 para Game Boy Advance. Ambientado en una sociedad hiperconectada de los años 2000, los jugadores controlan a Lan Hikari y a su programa de inteligencia artificial MegaMan.EXE, combatiendo virus informáticos y amenazas cibernéticas en una cuadrícula virtual dinámica de 3x3 utilizando chips de batalla coleccionables.', 'https://upload.wikimedia.org/wikipedia/en/c/cb/Megamanbattlenetwork_boxshot.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Mega_Man_Battle_Network_(video_game)'),
('fdb2f3f1-d928-5f2f-bd09-915f4737a233', 'pokemon-heartgold-soulsilver', 'Pokémon HeartGold and SoulSilver', 'Nintendo DS', 'nds', 'RPG', 'rpg', 2009, 'Game Freak', 'Pokémon HeartGold y SoulSilver son remakes magistrales lanzados en 2009 para Nintendo DS de los clásicos Oro y Plata. Ambientados en las regiones de Johto y Kanto, reinventaron la experiencia con gráficos tridimensionales mejorados, la mecánica de llevar a cualquier Pokémon acompañante caminando fuera de su Poké Ball y eventos cinematográficos protagonizados por Lugia y Ho-Oh.', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/PokemonHGSSBox.jpg/330px-PokemonHGSSBox.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_HeartGold_and_SoulSilver'),
('fdfa0d60-2d1a-5b31-8519-f179d0adea7c', 'mario-kart-ds', 'Mario Kart DS', 'Nintendo DS', 'nds', 'Carreras', 'carreras', 2005, 'Nintendo EAD', 'Mario Kart DS es una entrega histórica lanzada en 2005 para Nintendo DS. Introdujo por primera vez el juego multijugador en línea a través de la Conexión Wi-Fi de Nintendo, el modo Misiones exclusivo, la doble pantalla para radar y táctica, y pistas retro clásicas junto a legendarios circuitos nuevos como la Fortaleza Aérea (Airship Fortress).', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Mario_Kart_DS_cover.jpg/330px-Mario_Kart_DS_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Mario_Kart_DS'),
('2ced7b39-b3ac-55b6-81e9-dc4a39000411', 'zelda-phantom-hourglass', 'The Legend of Zelda: Phantom Hourglass', 'Nintendo DS', 'nds', 'Aventura', 'aventura', 2007, 'Nintendo EAD', 'The Legend of Zelda: Phantom Hourglass es una aventura directa de acción secuela de The Wind Waker, desarrollada por Nintendo EAD y lanzada en 2007 para Nintendo DS. Aprovechó de forma revolucionaria la pantalla táctil y el lápiz stylus para controlar los movimientos de Link, trazar la trayectoria del búmeran, navegar en barco y explorar el desafiante Templo del Rey del Mar.', 'https://upload.wikimedia.org/wikipedia/en/5/5e/The_Legend_of_Zelda_Phantom_Hourglass_Game_Cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Phantom_Hourglass'),
('7655f138-ac6c-5f35-92c4-071c72b4ca3d', 'new-super-mario-bros', 'New Super Mario Bros.', 'Nintendo DS', 'nds', 'Plataformas', 'plataformas', 2006, 'Nintendo EAD', 'New Super Mario Bros. es un videojuego de plataformas de desplazamiento lateral en 2.5D lanzado en 2006 para Nintendo DS. Marcó el esperado regreso de Mario al formato tradicional en 2D por primera vez desde Super Mario World, incorporando transformaciones gigantes como el Mega Champiñón y un apartado visual renovado que vendió más de 30 millones de copias.', 'https://upload.wikimedia.org/wikipedia/en/d/db/NewSuperMarioBrothers.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/New_Super_Mario_Bros.'),
('e26be229-bdd9-522e-a36b-915e5bdc98db', 'castlevania-dawn-of-sorrow', 'Castlevania: Dawn of Sorrow', 'Nintendo DS', 'nds', 'Acción', 'accion', 2005, 'Konami', 'Castlevania: Dawn of Sorrow es la secuela directa de Aria of Sorrow, desarrollada por Konami en 2005 para Nintendo DS. Continúa la historia de Soma Cruz enfrentando a una peligrosa secta que busca resucitar a un nuevo señor oscuro, aprovechando la pantalla táctil para dibujar ''Sellos Mágicos'' que encierran a los jefes y gestionando el sistema de almas con el mapa en pantalla superior.', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Castlevania_Dawn_of_Sorrow_NA_Cover.jpg/330px-Castlevania_Dawn_of_Sorrow_NA_Cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Castlevania:_Dawn_of_Sorrow'),
('8ec1cc12-780e-55cf-b436-59b15ecee583', 'pokemon-platinum', 'Pokémon Platinum', 'Nintendo DS', 'nds', 'RPG', 'rpg', 2008, 'Game Freak', 'Pokémon Platino es la versión mejorada de la cuarta generación en la región de Sinnoh, lanzada en 2008 para Nintendo DS. Destaca por la inclusión del Mundo Distorsión, un reino con gravedad alterada y perspectiva cambiante, la historia ampliada en torno a Giratina en su Forma Origen, la reaparición del Frente de Batalla y mejoras en la velocidad del combate.', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Pokemon_Platinum.png/330px-Pokemon_Platinum.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Platinum'),
('065acda6-2951-53b9-8f85-f8e2f0a97493', 'profesor-layton-villa-misteriosa', 'Professor Layton and the Curious Village', 'Nintendo DS', 'nds', 'Puzzle', 'puzzle', 2007, 'Level-5', 'El profesor Layton y la villa misteriosa es un aclamado juego de puzles y misterio desarrollado por Level-5 en 2007 para Nintendo DS. Sigue al arqueólogo británico Hershel Layton y a su aprendiz Luke en la villa de Saint-Mystère, resolviendo más de un centenar de ingeniosos acertijos integrados orgánicamente en una trama cautivadora estilo novela animada.', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Professor_Layton_and_the_Curious_Village_NA_Boxart.JPG/330px-Professor_Layton_and_the_Curious_Village_NA_Boxart.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Professor_Layton_and_the_Curious_Village'),
('b65ecd0a-fc53-587f-916f-463654a0f659', 'the-world-ends-with-you', 'The World Ends with You', 'Nintendo DS', 'nds', 'RPG', 'rpg', 2007, 'Square Enix', 'The World Ends with You es un innovador juego de rol de acción urbano desarrollado por Square Enix y Jupiter en 2007 para Nintendo DS. Ambientado en el bullicioso distrito de Shibuya en Tokio, los jugadores siguen a Neku Sakuraba en el mortal ''Juego de los Segadores'', utilizando simultáneamente la pantalla táctil inferior y los botones para controlar combates sincronizados en ambas pantallas.', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/The_World_Ends_With_You.jpg/330px-The_World_Ends_With_You.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/The_World_Ends_with_You'),
('2b66604d-3e94-5867-8b00-706295eace8e', 'gta-chinatown-wars', 'Grand Theft Auto: Chinatown Wars', 'Nintendo DS', 'nds', 'Acción', 'accion', 2009, 'Rockstar Leeds', 'Grand Theft Auto: Chinatown Wars es un juego de acción de mundo abierto desarrollado por Rockstar Leeds y Rockstar North en 2009 para Nintendo DS. Con una perspectiva cenital modernizada y sombreado cel-shading, sigue a Huang Lee en Liberty City haciendo un uso magistral de la pantalla táctil para robar vehículos, armar cócteles molotov y gestionar el submundo del comercio clandestino.', 'https://upload.wikimedia.org/wikipedia/en/7/75/ChinatownWars.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Grand_Theft_Auto:_Chinatown_Wars'),
('4155855b-4e82-5dc2-b221-e8dddf53f262', 'phoenix-wright-ace-attorney', 'Phoenix Wright: Ace Attorney', 'Nintendo DS', 'nds', 'Aventura', 'aventura', 2005, 'Capcom', 'Phoenix Wright: Ace Attorney es una novela visual y drama judicial interactivo desarrollado por Capcom en 2005 para Nintendo DS. Los jugadores encarnan al novato abogado defensor Phoenix Wright, investigando escenas de crímenes, interrogando testigos y gritando ¡Protesto! en el micrófono de la consola para exponer contradicciones lógicas en tribunales implacables.', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/73/Phoenix_Wright_-_Ace_Attorney_Coverart.png/330px-Phoenix_Wright_-_Ace_Attorney_Coverart.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Phoenix_Wright:_Ace_Attorney'),
('a929d35b-d484-5038-b5ca-524f24a82a45', 'super-mario-galaxy', 'Super Mario Galaxy', 'Wii', 'wii', 'Plataformas', 'plataformas', 2007, 'Nintendo EAD', 'Super Mario Galaxy es una obra maestra de plataformas en 3D desarrollada por Nintendo EAD Tokio y lanzada en 2007 para Wii. Revolucionó los juegos de plataformas al introducir mecánicas de gravedad esférica entre planetas y galaxias, acompañado de una banda sonora orquestada en vivo y el uso del mando Wii Remote para recoger trozos de estrella y realizar giros espaciales.', 'https://upload.wikimedia.org/wikipedia/en/7/76/SuperMarioGalaxy.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Super_Mario_Galaxy'),
('5acc0055-bb1f-5920-9c78-1feb0d9ac526', 'super-mario-galaxy-2', 'Super Mario Galaxy 2', 'Wii', 'wii', 'Plataformas', 'plataformas', 2010, 'Nintendo EAD', 'Super Mario Galaxy 2 es la continuación del aclamado juego espacial, lanzada por Nintendo en 2010 para Wii. Eleva el diseño de niveles a su máxima expresión creativa con nuevos potenciadores como Mario Nube y Mario Roca, además del regreso estelar del dinosaurio Yoshi con habilidades gravitacionales propias para devorar enemigos y superar retos plataformeros exigentes.', 'https://upload.wikimedia.org/wikipedia/en/6/65/Super_Mario_Galaxy_2_Box_Art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Super_Mario_Galaxy_2'),
('b0a97255-0caa-5790-8d10-7e4e65041da7', 'zelda-twilight-princess', 'The Legend of Zelda: Twilight Princess', 'Wii', 'wii', 'Aventura', 'aventura', 2006, 'Nintendo EAD', 'The Legend of Zelda: Twilight Princess es un juego de acción y aventura épico lanzado en 2006 para Wii como título de lanzamiento. Presenta un tono más maduro y oscuro en el reino de Hyrule, donde Link debe transformarse en lobo guiado por la misteriosa criatura Midna para liberar el mundo de la usurpación de las Sombras y restaurar la luz.', 'https://upload.wikimedia.org/wikipedia/en/0/0e/The_Legend_of_Zelda_Twilight_Princess_Game_Cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Twilight_Princess'),
('5d26941c-2900-5372-b1b3-4a07d27209f3', 'zelda-skyward-sword', 'The Legend of Zelda: Skyward Sword', 'Wii', 'wii', 'Aventura', 'aventura', 2011, 'Nintendo EAD', 'The Legend of Zelda: Skyward Sword fue lanzado en 2011 para Wii, celebrando el 25 aniversario de la franquicia. Narra el origen cronológico de la Espada Maestra y la leyenda de Hyrule, aprovechando la tecnología Wii MotionPlus para un control de espada preciso 1:1, donde cada corte y ángulo de ataque debe planificarse estratégicamente contra los enemigos.', 'https://upload.wikimedia.org/wikipedia/en/9/99/Legend_of_Zelda_Skyward_Sword_boxart.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Skyward_Sword'),
('640798a1-f482-53fa-929b-2222935204c9', 'super-smash-bros-brawl', 'Super Smash Bros. Brawl', 'Wii', 'wii', 'Lucha', 'lucha', 2008, 'Sora Ltd. / Game Arts', 'Super Smash Bros. Brawl es la tercera entrega de la saga de lucha entre franquicias de Nintendo, lanzada en 2008 para Wii. Introdujo por primera vez personajes invitados de compañías externas como Sonic the Hedgehog y Solid Snake, el modo historia cinematográfico ''El emisario subespacial'' y la mecánica de los Smash Finales que cambiaron el curso de cada combate.', 'https://upload.wikimedia.org/wikipedia/en/f/f3/SSBB_Cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Super_Smash_Bros._Brawl'),
('07ae998f-1107-5af6-86d0-e69599d097e1', 'metroid-prime-3', 'Metroid Prime 3: Corruption', 'Wii', 'wii', 'Shooter', 'shooter', 2007, 'Retro Studios', 'Metroid Prime 3: Corruption es la culminación de la trilogía Prime, desarrollada por Retro Studios y lanzada en 2007 para Wii. Aprovecha al máximo el puntero del Wii Remote para ofrecer una puntería y exploración inmersivas en primera persona, mientras Samus Aran combate la corrupción del Phazon en su cuerpo y se enfrenta a los cazarrecompensas oscuros y a Dark Samus.', 'https://upload.wikimedia.org/wikipedia/en/7/75/Metroid_Prime_3_Packaging.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Metroid_Prime_3:_Corruption'),
('e3c6dcb9-6346-5763-b0cd-049a9ade138d', 'mario-kart-wii', 'Mario Kart Wii', 'Wii', 'wii', 'Carreras', 'carreras', 2008, 'Nintendo EAD', 'Mario Kart Wii es uno de los videojuegos más vendidos de la historia, publicado por Nintendo en 2008. Introdujo por primera vez motocicletas con mecánicas de caballito y derrapes cerrados, carreras frenéticas de hasta 12 pilotos simultáneos, competencias en línea a nivel mundial y el accesorio Wii Wheel para control por movimiento intuitivo.', 'https://upload.wikimedia.org/wikipedia/en/d/d6/Mario_Kart_Wii.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Mario_Kart_Wii'),
('8d328be9-425a-53b0-8758-950a0af37c4c', 'xenoblade-chronicles', 'Xenoblade Chronicles', 'Wii', 'wii', 'RPG', 'rpg', 2010, 'Monolith Soft', 'Xenoblade Chronicles es un aclamado juego de rol japonés de mundo abierto desarrollado por Monolith Soft y lanzado en 2010 para Wii. Ambientado sobre los cuerpos colosales de dos titanes petrificados, Bionis y Mechonis, sigue a Shulk y su legendaria espada Monado, capaz de prever el futuro inmediato para alterar el destino en un vasto mundo lleno de exploración y combate en tiempo real.', 'https://upload.wikimedia.org/wikipedia/en/d/d9/Xenoblade_box_artwork.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Xenoblade_Chronicles_(video_game)'),
('885e5fa5-59f3-5ad7-9481-fc4f46760c8d', 'donkey-kong-country-returns', 'Donkey Kong Country Returns', 'Wii', 'wii', 'Plataformas', 'plataformas', 2010, 'Retro Studios', 'Donkey Kong Country Returns es un sobresaliente juego de plataformas desarrollado por Retro Studios en 2010 para Wii. Revivió la icónica franquicia creada por Rare con un diseño de niveles implacable, gráficos vibrantes en 2.5D, modo cooperativo para dos jugadores controlando a Donkey Kong y Diddy Kong, y los clásicos niveles en carretas de mina y barriles cañón.', 'https://upload.wikimedia.org/wikipedia/en/1/1f/Donkeykongcountryreturns.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Donkey_Kong_Country_Returns'),
('7806aa1a-5a9e-5f9f-8d85-7c574809fc16', 'wii-sports', 'Wii Sports', 'Wii', 'wii', 'Deportes', 'deportes', 2006, 'Nintendo EAD', 'Wii Sports es el histórico videojuego de simulación deportiva que acompañó a la consola Wii en su lanzamiento en 2006. Demostró el potencial de los controles de movimiento intuitivos a través de cinco disciplinas populares: tenis, béisbol, bolos, golf y boxeo, transformándose en un fenómeno cultural accesible para jugadores de todas las generaciones.', 'https://upload.wikimedia.org/wikipedia/en/5/54/Wii_Sports_Sleeve_Cover_Art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled', 'https://en.wikipedia.org/wiki/Wii_Sports'),
('f97c35cd-03f1-5d74-8548-1effda59b39f', 'super-mario-64', 'Super Mario 64', 'Nintendo 64', 'n64', 'Plataformas', 'plataformas', 1996, 'Nintendo EAD', 'Super Mario 64 es el legendario videojuego de plataformas 3D desarrollado por Nintendo EAD y lanzado en 1996 para Nintendo 64. Estableció las bases fundamentales del movimiento de cámaras analógicas y el diseño de mundos abiertos tridimensionales en la industria. Mario debe explorar las pinturas mágicas del castillo de la Princesa Peach para recolectar las Estrellas de Poder y derrotar a Bowser.', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Super_Mario_64.png/330px-Super_Mario_64.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Super_Mario_64'),
('e884b094-8343-56cd-8434-3bfeee2a60c0', 'zelda-ocarina-of-time', 'The Legend of Zelda: Ocarina of Time', 'Nintendo 64', 'n64', 'Aventura', 'aventura', 1998, 'Nintendo EAD', 'The Legend of Zelda: Ocarina of Time es ampliamente catalogado como uno de los mejores videojuegos jamás creados. Publicado en 1998 para Nintendo 64, introdujo el sistema de fijación de objetivos Z-Targeting y la mecánica de viajar en el tiempo siete años mediante la Ocarina del Tiempo y la Espada Maestra para detener al rey de las ladronas Ganondorf antes de que domine la Trifuerza.', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/57/The_Legend_of_Zelda_Ocarina_of_Time.jpg/330px-The_Legend_of_Zelda_Ocarina_of_Time.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Ocarina_of_Time'),
('2f1cc9c9-5e31-5602-827b-a4917fac753a', 'goldeneye-007', 'GoldenEye 007', 'Nintendo 64', 'n64', 'Shooter', 'shooter', 1997, 'Rare', 'GoldenEye 007 es un revolucionario juego de disparos en primera persona desarrollado por Rare y lanzado en 1997 para Nintendo 64. Basado en la película de James Bond de 1995, redefinió el género en consolas al priorizar misiones con sigilo y objetivos tácticos, además de popularizar las legendarias partidas multijugador a cuatro bandas a pantalla dividida.', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/13/GoldenEye_007_N64_cover.jpg/330px-GoldenEye_007_N64_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/GoldenEye_007_(1997_video_game)'),
('d354cc0b-2fa4-505a-88b3-b28cf9bfb470', 'mario-kart-64', 'Mario Kart 64', 'Nintendo 64', 'n64', 'Carreras', 'carreras', 1996, 'Nintendo EAD', 'Mario Kart 64 es el clásico videojuego de carreras desarrollado por Nintendo EAD y lanzado en 1996 para Nintendo 64. Dio el salto al modelado en tres dimensiones, introduciendo pistas emblemáticas como el Castillo de Bowser y la Senda Arcoíris, el temido caparazón azul con pinchos y soporte para carreras y batallas de globos de hasta 4 jugadores simultáneos.', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Mario_Kart_64.jpg/330px-Mario_Kart_64.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Mario_Kart_64'),
('3f4e1115-fcca-50de-b101-27c0bbbdfb02', 'super-smash-bros-64', 'Super Smash Bros.', 'Nintendo 64', 'n64', 'Lucha', 'lucha', 1999, 'HAL Laboratory', 'Super Smash Bros. es el título original de lucha y celebración de personajes creado por HAL Laboratory y dirigido por Masahiro Sakurai en 1999 para Nintendo 64. Reunió por primera vez a íconos como Mario, Link, Samus, Pikachu y Donkey Kong en frenéticos combates donde el objetivo es acumular daño porcentual para expulsar a los adversarios de la arena.', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Supersmashbox.jpg/330px-Supersmashbox.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Super_Smash_Bros._(video_game)'),
('2f209076-0026-58a1-9bf1-3c52d31dfc5a', 'banjo-kazooie', 'Banjo-Kazooie', 'Nintendo 64', 'n64', 'Plataformas', 'plataformas', 1998, 'Rare', 'Banjo-Kazooie es una obra maestra de plataformas de recolección desarrollada por Rare y publicada en 1998 para Nintendo 64. Los jugadores guían al oso Banjo y a la descarada ave Kazooie a través de nueve mundos no lineales repletos de acertijos y piezas de rompecabezas (Jiggies) para rescatar a la pequeña Tooty de las garras de la bruja Gruntilda.', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Banjo_Kazooie_Cover.png/330px-Banjo_Kazooie_Cover.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Banjo-Kazooie_(video_game)'),
('7eea3db3-f8c6-57b7-8e0f-39a3e9274560', 'star-fox-64', 'Star Fox 64', 'Nintendo 64', 'n64', 'Shooter', 'shooter', 1997, 'Nintendo EAD', 'Star Fox 64 (conocido en Europa como Lylat Wars) es un aclamado juego de disparos espacial sobre rieles lanzado en 1997 para Nintendo 64. Puso a prueba los reflejos de los jugadores a bordo de la nave Arwing junto a Fox McCloud y su escuadrón, siendo el primer título en incorporar actuación de voz cinematográfica y el accesorio Rumble Pak para vibración inmersiva en el mando.', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/StarFox64_N64_Game_Box.jpg/330px-StarFox64_N64_Game_Box.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Star_Fox_64'),
('d9ca65ba-3eda-5b5b-b342-8d585eeb9ac2', 'pokemon-snap', 'Pokémon Snap', 'Nintendo 64', 'n64', 'Simulación', 'simulacion', 1999, 'HAL Laboratory', 'Pokémon Snap es un innovador juego de fotografía y exploración en primera persona desarrollado por HAL Laboratory en 1999 para Nintendo 64. A bordo del vehículo todoterreno Zero-One en la Isla Pokémon, los jugadores deben capturar las mejores tomas de criaturas en su hábitat salvaje, utilizando manzanas y bombas de humo para provocar comportamientos únicos evaluados por el Profesor Oak.', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Pok%C3%A9mon_Snap_Coverart.png/330px-Pok%C3%A9mon_Snap_Coverart.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Snap'),
('9e28b343-5673-527d-ab1e-5fbaa270b808', 'zelda-majoras-mask', 'The Legend of Zelda: Majora''s Mask', 'Nintendo 64', 'n64', 'Aventura', 'aventura', 2000, 'Nintendo EAD', 'The Legend of Zelda: Majora''s Mask es la aclamada y oscura secuela directa de Ocarina of Time, lanzada en el año 2000 para Nintendo 64. Link queda atrapado en la tierra paralela de Términa, teniendo solo un ciclo recurrente de 72 horas para evitar que la Luna colisione contra la superficie, utilizando máscaras mágicas de transformación para alterar su forma y salvar a sus habitantes.', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/60/The_Legend_of_Zelda_-_Majora%27s_Mask_Box_Art.jpg/330px-The_Legend_of_Zelda_-_Majora%27s_Mask_Box_Art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Majora%27s_Mask'),
('69bdbc04-c908-59c0-8461-7d5edaa3f656', 'paper-mario-64', 'Paper Mario', 'Nintendo 64', 'n64', 'RPG', 'rpg', 2000, 'Intelligent Systems', 'Paper Mario es un encantador videojuego de rol desarrollado por Intelligent Systems y lanzado en el año 2000 para Nintendo 64. Combinó una original dirección de arte estilo papel en mundos tridimensionales con un sistema de combate dinámico de comandos de acción, donde Mario emprende una aventura junto a compañeros entrañables para recuperar los siete Espíritus Estelares arrebatados por Bowser.', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Papermario.jpg/330px-Papermario.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail', 'https://en.wikipedia.org/wiki/Paper_Mario_(video_game)')
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    platform = EXCLUDED.platform,
    platform_slug = EXCLUDED.platform_slug,
    genre = EXCLUDED.genre,
    genre_slug = EXCLUDED.genre_slug,
    release_year = EXCLUDED.release_year,
    developer = EXCLUDED.developer,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    source_url = EXCLUDED.source_url;
